name: Python Package Test

on: [push]

jobs:
  deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [ubuntu-16.04, ubuntu-18.04, windows-latest]
        os: [ubuntu-18.04]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        wget https://download.stereolabs.com/zedsdk/2.8/ubuntu18 -O ZED_SDK.run
        chmod +x ZED_SDK.run ; apt update; ./ZED_SDK.run --quiet -- silent
        python -m pip install --upgrade pip cython
        pip install setuptools wheel twine
        pip install -r requirements.txt
    - name: Build and publish
      #env:
      #  TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
      #  TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python setup.py build
      #python setup.py sdist bdist_wheel
      #twine upload dist/*
